import 'package:delivery_app_test/widget/custom_textfield.dart';
import 'package:flutter/material.dart';

import '../../data/utils.dart';
import '../../widget/custom_button.dart';

class SecurityTab extends StatelessWidget {
  const SecurityTab({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Two Factor Authentication(2FA)',
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
        const SizedBox(height: 16),
        CheckboxListTile(
            contentPadding: const EdgeInsets.symmetric(horizontal: 4),
            title: const Text(
              'Activate 2FA',
              style: TextStyle(fontWeight: FontWeight.w600),
            ),
            value: true,
            onChanged: (val) {}),
        const Text(
            '1. You will need an authenticator mobile app to complete this process, such as one of the following:'),
        Text(
          'Google Authenticator',
          style: TextStyle(
              color: Colors.green[900],
              fontSize: 16,
              fontWeight: FontWeight.bold),
        ),
        Text(
          'Microsoft Authenticator',
          style: TextStyle(
              color: Colors.green[900],
              fontSize: 16,
              fontWeight: FontWeight.bold),
        ),
        Text(
          'Dou Mobile',
          style: TextStyle(
              color: Colors.green[900],
              fontSize: 16,
              fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 16),
        const Text('2. Scan the QR code with your authenticator app.'),
        const Text(
          'if you can\'t scan the code, you can enter the secret key into your authenticator app.',
          style: TextStyle(color: Colors.grey),
        ),
        const SizedBox(height: 8),
        CustomButton(
          radius: 8,
          borderSide: borderSide,
          color: Colors.grey.shade100,
          child: const Padding(
            padding: EdgeInsets.symmetric(horizontal: 16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'HGTUOJHLO234EJDHFGDHYUD',
                  style: TextStyle(color: Colors.grey),
                ),
                Text(
                  'Copy',
                  style: TextStyle(color: Colors.green),
                )
              ],
            ),
          ),
        ),
        const SizedBox(height: 16),
        const Text(
          '3. After scanning the QR code above, enter the six digits generated by your authenticator',
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
        const SizedBox(height: 8),
        Row(
          children: List.generate(
              4,
              (i) => Padding(
                    padding: EdgeInsets.symmetric(horizontal: i == 0 ? 0 : 8),
                    child: const SizedBox(width: 50, child: CustomTextfield()),
                  )),
        ),
        const SizedBox(height: 16),
        RichText(
            text: const TextSpan(
                text: '4. ',
                children: [
                  TextSpan(
                    text: '**Note** ',
                    style: TextStyle(fontWeight: FontWeight.w700),
                  ),
                  TextSpan(
                      text:
                          'Make sure to store backup codes in a secure place in case you loose access to your primary authentication method.'),
                  TextSpan(text: ' Click here to reveal the backup codes.')
                ],
                style: TextStyle(color: Colors.black))),
        const SizedBox(height: 20),
        const Row(
          children: [
            Expanded(
              child: CustomButton(
                color: Colors.green,
                text: 'Cancel',
              ),
            ),
            SizedBox(width: 16),
            Expanded(
              child: CustomButton(
                color: Colors.grey,
                text: 'Verify',
              ),
            )
          ],
        )
      ],
    );
  }
}
